name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type: patch, minor, major'
        required: true
        default: 'patch'

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Bump version (no tag)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          cz bump --yes --no-tag --increment ${{ github.event.inputs.bump_type }}

          VERSION=$(cz version --project)
          BRANCH="chore/bump/v$VERSION"

          git checkout -b "$BRANCH"
          git push origin "$BRANCH"

          echo "Version bumped to $VERSION and pushed to branch $BRANCH"
